services:
  # The Relational Storage Engine
  postgres:
    image: postgres:15-alpine
    container_name: noa_postgres
    environment:
      POSTGRES_DB: noa_db
      POSTGRES_USER: engine_admin
      POSTGRES_PASSWORD: supersecretpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # The Celery Message Broker & Cache Layer
  redis:
    image: redis:7-alpine
    container_name: noa_redis
    ports:
      - "6379:6379"

  # Local AWS Cloud Emulator (SQS & Secrets Manager)
  localstack:
    image: localstack/localstack:4.14.0
    container_name: noa_aws_cloud
    ports:
      - "4566:4566"
    environment:
      - SERVICES=sqs,secretsmanager
      - AWS_DEFAULT_REGION=af-south-1
    volumes:
      - "localstack_data:/var/lib/localstack"

  backend:
    build:
      context: ./backend
    container_name: noa_backend
    depends_on:
      - postgres
      - redis
      - localstack
    ports:
      - "8000:8000"
    environment:
      SECRET_KEY: dev-secret-key
      DEBUG: "True"
      DATABASE_URL: postgres://engine_admin:supersecretpassword@postgres:5432/noa_db
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_DEFAULT_REGION: af-south-1
      SQS_ENDPOINT_URL: http://localstack:4566
      SQS_QUEUE_URL: http://localstack:4566/000000000000/telemetry-queue
      SQS_DLQ_URL: http://localstack:4566/000000000000/telemetry-dlq
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
    container_name: noa_frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://backend:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  postgres_data:
  localstack_data: