# Generated by Django 6.0.6 on 2026-06-09 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelemetryReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('composite_node_key', models.CharField(db_index=True, max_length=150)),
                ('timestamp', models.DateTimeField()),
                ('megawatts_delivered', models.DecimalField(decimal_places=4, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['composite_node_key', 'timestamp'], name='telemetry_t_composi_380797_idx')],
                'unique_together': {('composite_node_key', 'timestamp')},
            },
        ),
    ]
